steps:
  # Step 1: Restore, Build and Pack the project (creates .nupkg in nupkgs/)
  - name: 'mcr.microsoft.com/dotnet/sdk:7.0'
    id: 'Build and Pack'
    entrypoint: bash
    args:
      - -c
      - |
        dotnet restore MyApp.csproj
        dotnet build MyApp.csproj -c Release
        dotnet pack MyApp.csproj -c Release -o nupkgs
        ls -l nupkgs

  # Step 2: Upload the generated .nupkg file(s) to GCS bucket my-dotnet-packages
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload NuGet Package to GCS'
    entrypoint: bash
    args:
      - -c
      - |
        gsutil cp nupkgs/*.nupkg gs://my-dotnet-packages/

  # Step 3: Create Artifact Registry Docker repo if not exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create Artifact Registry repo if not exists'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        REPO_EXISTS=$$(gcloud artifacts repositories list --location=asia-south1 --format="value(NAME)" --filter="NAME=dotnet-repo" || echo "")
        if [ -z "$$REPO_EXISTS" ]; then
          echo "Creating Artifact Registry repository dotnet-repo"
          gcloud artifacts repositories create dotnet-repo \
            --repository-format=docker \
            --location=asia-south1 \
            --description="Docker repo for .NET app" || true
        else
          echo "Artifact Registry repository dotnet-repo already exists, skipping creation."
        fi

  # Step 4: Build BaGet Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build BaGet Docker Image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/onyx-antler-459216-j6/baget:latest'
      - '.'

  # Step 5: Push BaGet Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push BaGet Docker Image'
    args:
      - 'push'
      - 'gcr.io/onyx-antler-459216-j6/baget:latest'

  # Step 6: Deploy BaGet to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy BaGet to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'baget-service'
      - '--image'
      - 'gcr.io/onyx-antler-459216-j6/baget:latest'
      - '--region'
      - 'asia-south1'                       # Change to your region if needed
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'          # Remove if you want authentication
      - '--set-env-vars'
      - 'ASPNETCORE_ENVIRONMENT=Production,GCS_BUCKET=my-dotnet-packages,BAGET_API_KEY=my-strong-baget-api-key-123'

options:
  logging: CLOUD_LOGGING_ONLY
